resolution_width = 1024
resolution_height = 768
images =
{
	"entitytool.png",
	"linetool.png",
	"button.png",
	"entity.png",
	"wall.png",
	"debug1.png",
	"debug2.png",
	"debug3.png",
	"play.png",
	"stop.png",
	"redball.png",
	"sans-serif-11.png",
	"sans-serif-12.png",
	"sans-serif-14.png",
	"sans-serif-16.png",
	"sans-serif-18.png",
	"sans-serif-20.png",
	"sans-serif-22.png",
	"redball.png",	
	"quake1.png",
	"quake2.png",
	"quake3.png",
	"car_red.png",
	"minus.png",
	"one.png",
	"plus.png",
	"view.png",
	"grid.png",
	"grid3.png",
	"gwall.png",
	"grid_d.png",
	"wall_concrete.png"
}
objects =
{
	"car2.obj",
	"cube_tex.obj",
	"cube.obj",
	"dummy.obj",
	"cyborg.obj",
	"Pistol_1.obj",
	"Shotgun.obj",
	"Smg.obj",
	"Revolver.obj"
}
