resolution_width = 1280
resolution_height = 720
images =
{
	"entitytool.png",
	"linetool.png",
	"button.png",
	"entity.png",
	"quake1.png",
	"quake2.png",
	"quake3.png",
	"car_red.png",
	"grid.png",
	"grid3.png",
	"gwall.png",
	"grid_d.png",
	"wall_concrete.png",
	"metal03.png",
	"metal04.png",
	"stone02.png",
	"stone11.png",
	"concrete02.png",
	"wood02.png",
	"Transformer-Texture.png",
	"gl.png",
	"barrel.png",
	"concrete.png",
	"concretebench.png",
	"rustymetal.png",
	"scifi_barrel.png",
	"trash.png",
	"Keyboard.png"
}
objects =
{
	"car2.obj",
	"cube_tex.obj",
	"cube.obj",
	"dummy.obj",
	"cyborg.obj",
	"Pistol_1.obj",
	"Shotgun.obj",
	"Smg.obj",
	"Revolver.obj",
	"Transformer.obj",
	"grenadelauncher.obj",
	"barrel.obj",
	"trashcan.obj",
	"bench.obj",
	"trash.obj",
	"untitled.obj"
}
