/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-WindowsRelease1-359-g06611d82 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-WindowsRelease1-359-g06611d82"
#endif
#define SDL_REVISION_NUMBER 0
