#ifndef MOVEMENT_DEFS_H
# define MOVEMENT_DEFS_H

//# define OVERHEADCAMSPEED 0.028f
# define PLAYERRADIUS 16

//# define EDITOR_MOVESPEED 0.2f
//# define MOVESPEED 0.12f

# define PLAYER_WALKSPEED 0.1f
# define PLAYER_RUNSPEED 0.2f
# define PLAYER_ACCELERATION 0.1f
# define PLAYER_DECELERATION 0.01f
# define PLAYER_HEIGHT 50.0f
# define PLAYER_CROUCHHEIGHT 25.0f
//The speed player goes to crouch
# define PLAYER_CROUCHSPEED 0.1f
# define JUMP_DELAY 500


//# define MAXMOVEMENTSPEED 0.08f
# define ROTATESPEED 0.002f
# define MOUSESPEED 0.002f

#endif